spring:
  datasource:
    url: jdbc:mysql://10.2.130.95/volunteer?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: yb3685110
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  freemarker:
    template-loader-path: classpath:/templates
    request-context-attribute: request
    cache: false
  mvc:
    static-path-pattern: /static/**